export const urlToNameMapping = {
    "/": "메인",
    "/login": "로그인",
    "/signUp": "회원 가입",
    "/search": "검색",
    "/intro": "기관 소개",

    "/admin/member": "관리자 - 회원 관리",
    "/admin/edu": "관리자 - 교육 관리",
    "/admin/edu/add": "관리자 - 교육 추가",
    "/admin/eduHist": "관리자 - 교육 신청 관리",
    "/admin/rentHist": "관리자 - 대관 신청 관리",
    "/admin/org": "관리자 - 유관기관 관리",
    "/admin/board": "관리자 - 게시판 관리",
    "/admin/log": "관리자 - 로그 관리",
    "/admin/pay": "관리자 - 결제 관리",
    "/admin/ftmain": "관리자 - 여성인재 메인",
    "/admin/ftmain/ftw": "관리자 - 인재 신청 관리",
    "/admin/ftmain/ftc": "관리자 - 인재 매칭 관리",
    "/listchat": "관리자 - 채팅 문의",
    "/sms": "관리자 - SMS",

    "/edu/calendar": "교육 일정 캘린더",
    "/edu/list": "교육 리스트",
    "/edu/applylist": "교육 신청 내역",

    "/post/1": "공지사항",
    "/post/2": "언론보도",
    "/imgPost/3": "세종시 및 단체 소식",
    "/imgPost/4": "여플 소식",
    "/imgPost/5": "뉴스레터",
    "/qna": "자주 묻는 질문",
    "/csl/7": "노무 상담 게시판",
    "/csl/8": "온라인 상담 게시판",
    "/error": "에러 페이지",
    "/post/new": "게시글 작성",

    "/rent/process": "대관 절차",
    "/rent/status": "대관 현황 및 신청",
    "/rent/review": "대관 후기",
    "/rent/review/write": "대관 후기 작성",

    "/mypage/edu": "내 교육 내역",
    "/mypage/rent": "내 대관 내역",
    "/mypage/active": "내 활동",
    "/mypage/ftw": "내 여성 인재",
    "/mypage/club": "내 소모임 목록",
    "/mypage/csl": "내 상담 내역",
    "/mypage/infoEdit": "내 정보 수정",
    "/mypage/infoEditSuccess": "내 정보 수정 완료",

    "/clubsMain": "소모임 메인",
    "/clubs/new": "소모임 신청",

    "/ftmain": "인재풀 메인",
    "/ftw/new": "인재 등록 신청",
    "/ftc/new": "인재 매칭 신청",

    "/chat":"챗봇",
}